apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gs-rest-service
  name: gs-rest-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gs-rest-service
  strategy: {}
  template:
    metadata:
      labels:
        app: gs-rest-service
    spec:
      containers:
      - image: 3ill/gs-rest-service
        name: gs-rest-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
              
status: {}