apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
         name: regcred
         items:
         - key: .dockerconfigjson
           path: config.json
  - name: jenkins-m2-pv
    persistentVolumeClaim:
      claimName: jenkins-m2-pv-claim
  - name: docker-socket
    emptyDir: {}
  # - name: docker-daemon-config
  #   configMap:
  #     name: harbor-dns-configmap
  containers:
  - name: maven
    image: maven:3.8.4-openjdk-11
    command: ['sleep', '60m']
    tty: true
    resources:
      limits:
         cpu: 350m
         memory: 4Gi
      requests:
         cpu: 150m
         memory: 4Gi
    volumeMounts:
      - mountPath: "/m2"
        name: jenkins-m2-pv
  - name: docker
    image: docker:20.10.12
    env:
      - name: CONTAINER_ENV_VAR
        value: docker
    command: ['sleep', '60m']
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 150m
        memory: 64Mi
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  - name: docker-daemon
    image: docker:20.10.12-dind
    env:
      - name: CONTAINER_ENV_VAR
        value: docker-daemon
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
    # - name: docker-daemon-config
    #   mountPath: /etc/docker/
    #   readOnly: true
  - name: argocd
    image: docker.io/3ill/argocd
    command: ['sleep', '60m']
    tty: true
    resources:
      limits:
         cpu: 500m
         memory: 800Mi
      requests:
         cpu: 150m
         memory: 400Mi
  - name: trivy
    image: aquasec/trivy:0.23.0
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 350m
        memory: 600Mi
      requests:
        cpu: 150m
        memory: 300Mi
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run