apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven/3.8.4-openjdk-11
    command: ['sleep', '60m']
    tty: true
    resources:
      limits:
         cpu: 350m
         memory: 600Mi
      requests:
         cpu: 150m
         memory: 300Mi
  - name: trivy
    image: aquasec/trivy:0.22.0
    command: ['sleep', '60m']
    tty: true
    resources:
      limits:
         cpu: 350m
         memory: 600Mi
      requests:
         cpu: 150m
         memory: 300Mi